### ISSUE TITLE
(9.6) email issue

### ISSUE THREAD

**Issue by mahi1071** [tourist1998/Xcomp#10]
In the email field of the signup form strings without @ and "." are accepted.

**Comment by mahi1071** [comment]
(9.6)
Username : asha@123

password : @pcstcs123

NGO's name : asha

phone no : 8762340980

Director's name : Biswa Mal

Director's Phone no : 9807901234

email : b

Address : 9/4 thakurpukur lane,kolkata

**Comment by biswa9898** [comment]
View > NGOSignup
View > DonorSignup
