### ISSUE TITLE
(12.1)(11.1) Head Issue.

### ISSUE THREAD

**Issue by mahi1071** [tourist1998/Xcomp#11]
In the post food need and post food availability, the no. of heads field is accepting very large inputs which is not feasible. There must be an upper limit for the maximum number of heads.

**Comment by mahi1071** [comment]
(12.1)
Number of people the food can fed : 10000

Location : Ultadanga

Type of food : Non Veg

Pickup Time : 5pm

(11.1)
Location : SaltLake

Type of Food : Non Veg

Number of people you need to feed : 1000

Pickup Time : 4pm

Days you serve : ['tue','wed']

**Comment by biswa9898** [comment]
View > NGOpostneed
