### ISSUE TITLE
(9.8) Same phone number issue.

### ISSUE THREAD

**Issue by mahi1071** [tourist1998/Xcomp#13]
The system is accepting two people having the same phone number which is an error.

**Comment by mahi1071** [comment]
(9,8)

Username : usha@473

password : 12987542

NGO's name : usha

phone no : 8544283866

Director's name : Mita Dal

Director's Phone no : 9807901267

email : ammacode44@gmail.com

Address : Haldiram more,Kolkata

**Comment by tourist1998** [comment]
// Use Number 13 
        var user2 = await User.find();
        for(var i=0;i<user2.length;i++) {
            if(user2[i].UserName == req.body.UserName || user[i].DirectorPhone == req.body.DirectorPhone || user[i].Email == req.body.Email) {
                return next('There is some issue in our project');
            } 
        }
This will cause error if 2 user have same UserName or Same phone no or Same director Phone Number.
