### ISSUE TITLE
(UI) Food Type Matching Issue

### ISSUE THREAD

**Issue by mahi1071** [tourist1998/Xcomp#14]
Though only one type of food is selected by the NGO in the Post Food Need different types of food is shown to him in the View Pickup List.

**Comment by tourist1998** [comment]
for(var i=0;i<unique.length;i++) {
        const availabilityByLocation = await Available.find({'location' : unique[I] , 'type_of_food' : type2 }); 
        if(availabilityByLocation.length != 0) // To remove empty object from our list 
        list.push(availabilityByLocation);
    }

**Comment by biswa9898** [comment]
Controller > AllocationMGR > GetDonorList
