### ISSUE TITLE
(9.4)(13.3) Phone no. Issue

### ISSUE THREAD

**Issue by mahi1071** [tourist1998/Xcomp#9]
In the signup form phone number field is accepting plain alphabetic strings. But the phone number should be a 10 digit number with the starting number within a range 6-9 as in INDIA.

**Comment by mahi1071** [comment]
(9.4)
Username : asha@123

password : @pcstcs123

NGO's name : asha

phone no : abcdefghij

Director's name : Biswa Mal

Director's Phone no : 9807901234

email : ashafoundation01@gmail.com

Address : 9/4 thakurpukur lane,kolkata 

(13.3)
Username :Saima123

password : @bombom12

Donor's name : Saima Restaurent

phone no : abcdefghij

Address : 10/4 ultadanga lane,kolkata 711110

Type of Food Served : Veg

Area of Service : ultadanga

**Comment by biswa9898** [comment]
Controller > UserController > signup
